- name: Update Aptitude
  apt: update_cache=yes cache_valid_time=3600

- name: Add commonly needed programs
  apt: name={{ item }} state=latest
  with_items:
    - screen
    - unzip
    - raspi-config
