#!/bin/sh
#
# Simple cron script - save the current clock periodically in case of
# a power failure or other crash
OVERLAY=/sbin/overlayctl
if (command -v fake-hwclock >/dev/null 2>&1) ; then
  $OVERLAY unlock
  fake-hwclock save
  cp /etc/fake-hwclock.data /overlay/robase/etc/fake-hwclock.data
  $OVERLAY lock
fi
